name: CI and Sync Fork

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm globally & ensure in PATH
        run: |
          npm install -g pnpm
          echo "$(npm bin -g)" >> $GITHUB_PATH
          pnpm -v

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Prettier check (non-blocking)
        run: pnpm format:check || echo "Prettier issues (not blocking)"

      - name: Test
        run: pnpm test

  sync-to-fork-alternative:
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_FORK_TOKEN }}
        run: |
          echo "${{ secrets.PERSONAL_FORK_TOKEN }}" | gh auth login --with-token

      - name: Sync to personal fork using GitHub CLI
        run: |
          echo "=== Syncing using GitHub CLI ==="
          gh repo sync dnjfht/be-beam.site --source ${{ github.repository }} --branch main
          echo "✅ Sync completed via GitHub CLI"
