on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm globally & add to PATH
        run: |
          npm install -g pnpm
          echo "$(npm bin -g)" >> $GITHUB_PATH
          pnpm -v

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm format:check || echo "Prettier issues (not blocking)"
      - run: pnpm test

  sync-to-fork:
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm globally & add to PATH
        run: |
          npm install -g pnpm
          echo "$(npm bin -g)" >> $GITHUB_PATH
          pnpm -v

      - run: pnpm install

      - name: Push to personal fork
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci-bot@example.com"
          git remote add fork https://x-access-token:${{ secrets.PERSONAL_FORK_TOKEN }}@github.com/dnjfht/be-beam.site.git
          git push -f fork main
