on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm globally & ensure in PATH
        run: |
          npm install -g pnpm
          echo "$(npm bin -g)" >> $GITHUB_PATH
          pnpm -v

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Prettier check (non-blocking)
        run: pnpm format:check || echo "Prettier issues (not blocking)"

      - name: Test
        run: pnpm test

  sync-to-fork:
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm globally & ensure in PATH
        run: |
          npm install -g pnpm
          echo "$(npm bin -g)" >> $GITHUB_PATH
          pnpm -v

      - name: Install dependencies
        run: pnpm install

      - name: Set up Git credentials
        run: |
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.PERSONAL_FORK_TOKEN }}@github.com" > ~/.git-credentials

      - name: Push to personal fork
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci-bot@example.com"
          git remote remove fork || true
          git remote add fork https://github.com/dnjfht/be-beam.site.git
          git push -f fork main
