name: CI and Sync Fork

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm globally & ensure in PATH
        run: |
          npm install -g pnpm
          echo "$(npm bin -g)" >> $GITHUB_PATH
          pnpm -v

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Prettier check (non-blocking)
        run: pnpm format:check || echo "Prettier issues (not blocking)"

      - name: Test
        run: pnpm test

  sync-to-fork:
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # 기본 토큰으로 체크아웃

      - name: Set up Git user
        run: |
          git config --global user.name "dnjfht"
          git config --global user.email "117057638+dnjfht@users.noreply.github.com"

      - name: Sync to personal fork
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_FORK_TOKEN }}
        run: |
          echo "=== Debug Information ==="
          echo "Current repository: ${{ github.repository }}"
          echo "Current branch: $(git branch --show-current)"
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Token exists: $(if [ -n "${PERSONAL_TOKEN}" ]; then echo "YES"; else echo "NO"; fi)"

          # 현재 상태 확인
          echo "=== Current Git Status ==="
          git remote -v
          git branch -vv
          git log --oneline -3

          # Personal fork를 새로운 remote로 추가 (origin은 건드리지 않음)
          echo "=== Adding personal fork remote ==="
          git remote add personal-fork https://x-access-token:${PERSONAL_TOKEN}@github.com/dnjfht/be-beam.site.git

          # Remote 연결 테스트
          echo "=== Testing remote connection ==="
          if git ls-remote personal-fork HEAD; then
            echo "✅ Personal fork remote accessible"
          else
            echo "❌ Personal fork remote not accessible"
            exit 1
          fi

          # 현재 main 브랜치를 personal fork의 main으로 강제 푸시
          echo "=== Pushing to personal fork ==="
          if git push --force personal-fork main:main; then
            echo "✅ Successfully synced to personal fork"
          else
            echo "❌ Failed to sync to personal fork"
            
            # 디버깅을 위한 추가 정보
            echo "=== Additional Debug Info ==="
            git show-ref
            git remote show personal-fork
            exit 1
          fi

          # 최종 확인
          echo "=== Final Verification ==="
          REMOTE_COMMIT=$(git ls-remote personal-fork main | cut -f1)
          LOCAL_COMMIT=$(git rev-parse HEAD)
          echo "Local commit: $LOCAL_COMMIT"
          echo "Remote commit: $REMOTE_COMMIT"

          if [ "$LOCAL_COMMIT" = "$REMOTE_COMMIT" ]; then
            echo "✅ Sync verified successfully"
          else
            echo "⚠️ Commits don't match, but push completed"
          fi
