name: CI & Deploy to Personal Repo

on:
  push:
    branches: [main] # 조직 저장소의 main 브랜치에 push되었을 때 작동

jobs:
  ci:
    name: Run CI (ESLint, Prettier, Test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Run Format Check
        run: pnpm format:check || echo "Prettier issues (not blocking)"

      - name: Run Tests
        run: pnpm test

  sync-to-fork:
    name: Push to Personal Fork
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Push to Personal Fork
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci-bot@example.com"

          git remote add fork https://x-access-token:${{ secrets.PERSONAL_FORK_TOKEN }}@github.com/dnjfht/be-beam.site.git
          git push -f fork main
